"""
channel_programmer.py — DB queries, liquidsoap generator, and deploy logic
for the MHBN channel programmer.

The generator produces a complete channels.liq from channel_category_weights
stored in the mhbn database. The boilerplate (settings, encoder, helpers) is
static; only the per-channel source lists and weights are dynamic.

Deploy flow:
  1. generate_liq() → string
  2. deploy_to_zikzak(content) → writes to ZIKZAK via SSH, restarts service
"""

import subprocess
import textwrap

import psycopg2
import psycopg2.extras

from config import (
    DATABASE_URL,
    ZIKZAK_HOST, ZIKZAK_USER, ZIKZAK_JUMP,
    ZIKZAK_LIQ_PATH, ZIKZAK_LIQ_SERVICE,
)


# ── DB helpers ───────────────────────────────────────────────────────────────

def get_conn():
    return psycopg2.connect(DATABASE_URL)


def get_channel_configs():
    """Return all channel configs ordered by channel name."""
    with get_conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("""
                SELECT channel, label, channel_type,
                       updated_at AT TIME ZONE 'UTC' AS updated_at
                FROM channel_configs
                ORDER BY channel
            """)
            return [dict(r) for r in cur.fetchall()]


def get_channel_weights(channel):
    """Return weights for a channel, annotated with media_files stats."""
    with get_conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("""
                SELECT
                    w.id,
                    w.category,
                    w.subdir,
                    w.weight,
                    w.enabled,
                    COALESCE(s.file_count, 0)::int   AS file_count,
                    ROUND(COALESCE(s.total_hours, 0)::numeric, 1) AS total_hours
                FROM channel_category_weights w
                LEFT JOIN (
                    SELECT category, subdir,
                           COUNT(*)                   AS file_count,
                           SUM(duration_secs) / 3600.0 AS total_hours
                    FROM media_files
                    WHERE is_active = true
                    GROUP BY category, subdir
                ) s ON s.category = w.category
                    AND (s.subdir = w.subdir
                         OR (s.subdir IS NULL AND w.subdir IS NULL))
                WHERE w.channel = %s
                ORDER BY w.enabled DESC, w.weight DESC, w.category, w.subdir
            """, (channel,))
            return [dict(r) for r in cur.fetchall()]


def get_available_sources():
    """Return all (category, subdir) pairs present in media_files."""
    with get_conn() as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
            cur.execute("""
                SELECT category, subdir,
                       COUNT(*)                    AS file_count,
                       ROUND(SUM(duration_secs) / 3600.0, 1) AS total_hours
                FROM media_files
                WHERE is_active = true
                GROUP BY category, subdir
                ORDER BY category, subdir
            """)
            return [dict(r) for r in cur.fetchall()]


def save_channel_weights(channel, weights):
    """Replace all weights for a channel.

    weights: list of dicts with keys: category, subdir (or null), weight, enabled
    """
    with get_conn() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "DELETE FROM channel_category_weights WHERE channel = %s",
                (channel,)
            )
            for w in weights:
                cur.execute("""
                    INSERT INTO channel_category_weights
                        (channel, category, subdir, weight, enabled)
                    VALUES (%s, %s, %s, %s, %s)
                """, (
                    channel,
                    w["category"],
                    w.get("subdir") or None,
                    max(1, min(20, int(w.get("weight", 1)))),
                    bool(w.get("enabled", True)),
                ))
            cur.execute(
                "UPDATE channel_configs SET updated_at = NOW() WHERE channel = %s",
                (channel,)
            )
        conn.commit()


# ── Liquidsoap generator ─────────────────────────────────────────────────────

# Static boilerplate — settings, encoder, helper functions.
# Keep in sync with zikzak/liquidsoap/channels.liq.baseline in the repo.
_LIQ_HEADER = """\
# channels.liq — generated by MHBN channel programmer
# Edit via the channel programmer UI; do not edit by hand.
# Source of truth: channel_category_weights table in mhbn DB on loki.

settings.frame.video.width.set(960)
settings.frame.video.height.set(720)

settings.server.telnet.set(true)
settings.server.telnet.bind_addr.set("127.0.0.1")
settings.server.telnet.port.set(1234)

log.file.set(true)
log.file.path.set("/home/max/liquidsoap/channels.log")

# NVENC: canvas is already 960x720, no scale filter needed
let nvenc_cmd_base =
  "-r 25 " ^
  "-vf \\"format=yuv420p\\" " ^
  "-c:v h264_nvenc -preset p4 -profile:v high " ^
  "-b:v 1400k -maxrate 1400k -bufsize 2800k -g 60 " ^
  "-c:a aac -b:a 128k -ac 2 -ar 44100 " ^
  "-af \\"aresample=async=1\\" " ^
  "-max_muxing_queue_size 1024 " ^
  "-f mpegts "

def encoder_cmd(mount) =
  nvenc_cmd_base ^ "icecast://source:noisebridge@localhost:8000" ^ mount
end

let media = "/mnt/media"

def dir_src(d) =
  playlist(mode="randomize", reload_mode="watch", d)
end

def is_insert(meta) =
  f = meta["filename"]
  string.contains(prefix="#{media}/interstitials", f) or
  string.contains(prefix="#{media}/commercials", f)
end

def push_nowplaying(local_mount, relay_mount, meta) =
  filename = meta["filename"]
  if filename != "" and not is_insert(meta) then
    label = string.trim(
      (process.run(
        "f=" ^ string.quote(filename) ^ "; " ^
        "title=$(basename \\"$f\\" | sed 's/\\\\.[^.]*$//'); " ^
        "cat=$(echo \\"$f\\" | cut -d/ -f4); " ^
        "if [ -n \\"$cat\\" ]; then raw=\\"$title [$cat]\\"; else raw=\\"$title\\"; fi; " ^
        "echo \\"$raw\\" | python3 -c \\"" ^
        "import sys, unicodedata; " ^
        "s = sys.stdin.read().strip(); " ^
        "s = unicodedata.normalize('NFKD', s); " ^
        "print(''.join(c for c in s if ord(c) < 128))" ^
        "\\""
      )).stdout
    )
    curl_meta = "curl -sf --get --data-urlencode " ^ string.quote("song=" ^ label) ^ " --data mode=updinfo "
    ignore(process.run(curl_meta ^ string.quote("http://admin:noisebridge@localhost:8000/admin/metadata?mount=" ^ local_mount)))
    ignore(process.run(curl_meta ^ string.quote("http://admin:k0l9j8@nthmost.com:8000/admin/metadata?mount=" ^ relay_mount)))
  end
end

# ── ch1: music channel (not DB-driven) ────────────────────────────────────────
def make_music_channel(id) =
  music_long    = dir_src("#{media}/music/long")
  music_short   = dir_src("#{media}/music/short")
  interstitials = dir_src("#{media}/interstitials")
  music_mix = random(weights=[2, 3], [music_long, music_short])
  s = rotate([music_mix, interstitials])
  s.on_track(fun(meta) -> push_nowplaying("/#{id}.ts", "/mhbn-#{id}.ts", meta))
  mksafe(s)
end

"""


def _source_path(category, subdir):
    """Build the media directory path for a (category, subdir) pair."""
    if subdir:
        return f'"#{{media}}/{category}/{subdir}"'
    return f'"#{{media}}/{category}"'


def _generate_programmed_channel(ch_id, weights):
    """Generate a make_<ch_id>() function from a list of weight dicts."""
    enabled = [w for w in weights if w["enabled"]]
    if not enabled:
        # Fallback to prelinger if everything is disabled
        enabled = [{"category": "prelinger", "subdir": None, "weight": 1}]

    weight_list = ", ".join(str(w["weight"]) for w in enabled)
    sources = "\n".join(
        f'    dir_src({_source_path(w["category"], w["subdir"])}),'
        for w in enabled
    )

    return textwrap.dedent(f"""\
        def make_{ch_id}() =
          s = random(weights=[{weight_list}],
            [
        {sources}
            ])
          s.on_track(fun(meta) -> push_nowplaying("/{ch_id}.ts", "/mhbn-{ch_id}.ts", meta))
          mksafe(s)
        end
        """)


def generate_liq():
    """Generate a complete channels.liq from the current DB config."""
    configs = get_channel_configs()
    lines = [_LIQ_HEADER]
    lines.append("# ── Programmed channels (DB-driven) ─────────────────────────────────────────\n")

    for cfg in configs:
        ch = cfg["channel"]
        if cfg["channel_type"] == "music":
            continue  # handled by static make_music_channel above
        weights = get_channel_weights(ch)
        lines.append(_generate_programmed_channel(ch, weights))

    lines.append("# ── Channel assignments ──────────────────────────────────────────────────────\n")

    for cfg in configs:
        ch = cfg["channel"]
        if cfg["channel_type"] == "music":
            lines.append(f'{ch} = make_music_channel("{ch}")')
        else:
            lines.append(f'{ch} = make_{ch}()')

    lines.append("")
    for cfg in configs:
        ch = cfg["channel"]
        lines.append(
            f'output.external.ffmpeg(id="enc_{ch}", show_command=true, '
            f'reopen_on_error=fun (_)->5., encoder_cmd("/{ch}.ts"), {ch})'
        )

    return "\n".join(lines) + "\n"


# ── Deploy ───────────────────────────────────────────────────────────────────

def _ssh(args, stdin=None):
    """Run an SSH command to zikzak. Returns (stdout, stderr, returncode)."""
    ssh_base = [
        "ssh",
        "-o", "StrictHostKeyChecking=no",
        "-o", f"ProxyJump={ZIKZAK_JUMP}",
        f"{ZIKZAK_USER}@{ZIKZAK_HOST}",
    ]
    result = subprocess.run(
        ssh_base + args,
        input=stdin,
        capture_output=True,
    )
    return result.stdout, result.stderr, result.returncode


def deploy_to_zikzak(liq_content):
    """Write channels.liq to zikzak and restart liquidsoap.

    Raises RuntimeError on failure.
    """
    content_bytes = liq_content.encode()

    # Write file via stdin
    _, stderr, rc = _ssh(
        [f"cat > {ZIKZAK_LIQ_PATH}"],
        stdin=content_bytes,
    )
    if rc != 0:
        raise RuntimeError(f"write failed: {stderr.decode().strip()}")

    # Restart service
    _, stderr, rc = _ssh(
        ["sudo", "systemctl", "restart", ZIKZAK_LIQ_SERVICE],
    )
    if rc != 0:
        raise RuntimeError(f"restart failed: {stderr.decode().strip()}")
