[Service]
Environment=LD_LIBRARY_PATH=/opt/ffmpeg7/lib
Environment=LIQ_CACHE_SYSTEM_DIR=/home/max/.cache/liquidsoap
Environment=LIQ_CACHE_USER_DIR=/home/max/.cache/liquidsoap
ExecStart=
ExecStart=/opt/liquidsoap-2.5/bin/liquidsoap --stdlib /opt/liquidsoap-2.5/share/liquidsoap-lang/libs/stdlib.liq /home/max/liquidsoap/channels.liq
